wsargent/docker-cheat-sheet

README.md

Added verification from the docker inspect documentation https://docs.docker.com/reference/commandline/cli/#inspect

Updated "Get IP Address"

---

README.md

Just added a couple more links to  docker linking and volumes

Add some links on linking and volumes

---

README.md

A tool to cleanup volumes, provided as a ephemeral conatiner.

volumes cleanup

---

README.md

Update the using of fig part to docker-compose

---

README.md

The exec command can be used to launch another process in an already running container.

Added how to poke around in a running container

---

README.md

The option name is now `--volumes-from`.

Fix `-volume-from`

---

README.md

Docker cp allows now to copy files from local filesystem to container

Update import/export section

---

README.md

* GitHub case.
* HTTP → HTTPS where possible.

Fix README.md misc things

---

README.md

Fixes https://github.com/wsargent/docker-cheat-sheet/issues/59

Add networks, fix port feature.

---

zh-cn/README.md

add Simplified Chinese version.

docs: add Simplified Chinese version 

---

README.md

Did this change at some point?

change docker volumes to docker volume

---

zh-cn/README.md

#68 Fix link to pause subcommand
#69 Update README
#70 change docker volumes to docker volum
#71 Add info about LABEL
#72 Update README URLs based on HTTP

docs(zh-cn): update zh-cn/README.md

---

zh-cn/README.md

#75 Correct .dockerignore link
#76 Add note to avoid ADD and use COPY instead.

docs(zh-cn): update zh-cn/README.md(#75 #76)

---

zh-cn/README.md

#78 Update broken link to terms/layer

docs(zh-cn): update zh-cn/README.md(#78)

---

README.md

Added some common/popular text editors and their syntax highlighting modules

Syntax highlighting for Dockerfile

---

README.md

Provide documentation to map an additional port in a running container.

Update networking in a live container

---

zh-cn/README.md

docs(zh-cn): Update README.md

---

README.md

some urls where missing a /engine/ path

update of docs.docker.com urls

---

README.md

This document is awesome so I'd like to contribute! 
Update a few sentences for clarity and verb usage. Add a link to the TextMate Dockerfile syntax highlighter. Minor formatting updates for consistency.

Minor updates for clarity

---

README.md

This section is about why docker, not about why a cheat sheet.

Why -> Why Docker

---

README.md

Added options -td and --name for docker run with the full explanation about them.

Added options -td and --name for docker run

---

README.md

VS Code with the Docker extension provides a great experience to fiddle around with dockerfiles

Add VS Code as common text editor

---

README.md

Just wanted to add that is possible to mount files as volumes. 
Don't know if that is worth mentioning. But it can be useful if you want to toy around with a image from [Docker Hub](https://hub.docker.com) without writing your own Dockerfile.

Volumes can be files

---

zh-cn/README.md

The AD should not be in zh-cn/README.md...
Fix #148

Update zh-cn/README.md - remove AD

---

README.md

Delete all containers (force!! running or stopped containers)

Add tips: Delete all containers command

---

README.md

Add a example link to write Dockerfile

Add some useful links for writing Dockerfile

---

ru/README.md

Added Russian translate

---

README.md
zh-cn/README.md

Found this project by a recommendation in a Chinese community, love it with all common things about docker are introduced here. 
But there're some old links which are outdated or deprecated by Docker and the Chinese version doesn't be well-translated. So I decided to improve it myself. After a couple of days, this what you see is my work.
I'm not a pro in either Docker or translating. If anyone finds anything wrong, please let me know. Thanks.

A lot of Improvement

---

README.md

add how to detach a container if we are in the container's bash.

add how to detach a container

---

README.md

https://docs.docker.com/engine/reference/builder/#add
https://docs.docker.com/engine/reference/builder/#copy

Mention `--chown` for `ADD`/`COPY`

---

README.md

Add Docker-Compose Commands

---

README.md
ru/README.md
zh-cn/README.md

- add contents description
- add shell command result
- README links correction
Hello,
I add some detail of contents description, and docker version command result in code block,
for Chinese version.
And fix the problem in #178

README links correction

---

README.md

Please label this pull request with `hacktoberfest-accepted`.
I noticed this highly starred repo has no instructions for windows and windows server endpoints, so I added Microsoft's solutions and other goodies that users can enjoy docker with. After installation, windows users are able to follow the rest of the cheat sheet.

Created Windows instructions and prerequisites

---

pt-br/README.md

It's just a translation to the Brazilian-Portuguese language =)

Brazilian-Portuguese (pt-br) translation

---

es-es/README.md

Spanish translation

---

README.md
es-es/README.md
pt-br/README.md
ru/README.md
zh-cn/README.md

- `brew cask install docker` -> `brew install --cask docker`, [Official Document](https://formulae.brew.sh/cask/docker#default)
- update the link of "Docker Desktop for Windows"

Update Homebrew command and Docker Desktop for Windows link
